//! Binary encoding of class files
//!
//! This handles serializing class files into bytes and includes data types that match as closely
//! as possible the [JVM specification for the structure of class files][0]. Usually code is
//! generated by creating a [`crate::jvm::model::Class`] and then converting it into a
//! [`ClassFile`].
//!
//! [0]: https://docs.oracle.com/javase/specs/jvms/se17/html/jvms-4.html

mod attribute;
mod class;
mod constants;
mod field;
mod method;
mod serialize;
mod version;

pub use attribute::*;
pub use class::*;
pub use constants::*;
pub use field::*;
pub use method::*;
pub use serialize::*;
pub use version::*;
