[package]
name = "wasm2jar-bin"
version = "0.1.0"
authors = ["Alec Theriault <alec.theriault@gmail.com>"]
edition = "2018"

[dependencies]
wasm2jar = { path = "../../lib" }
clap = "2.33"
log = "0.4"
env_logger = "0.9"

[[bin]]
name = "wasm2jar"
path = "src/main.rs"
