[package]
name = "wast2jar-bin"
version = "0.1.0"
authors = ["Alec Theriault <alec.theriault@gmail.com>"]
edition = "2021"
rust-version = "1.63"
repository = "https://github.com/harpocrates/wasm2jar/tree/main/bin/wast2jar"
categories = ["command-line-utilities", "wasm", "compilers"]
description = "WAST tester for WASM to JAR converter"

[dependencies]
wasm2jar = { path = "../../lib" }
wast = "49.0.0"
clap = { version = "4.0", features = ["cargo"] }
log = "0.4"
env_logger = "0.9"
termcolor = "1.1"
walkdir = "2.3"

[[bin]]
name = "wast2jar"
path = "src/main.rs"
